type CookingStyle {
    id: Int!
    label: String!
    cooking_style_restaurants: [CookingStyleRestaurant]!
    created_at: String!
    updated_at: String
}

# Entité de liaison entre CookingStyle et Restaurant
type CookingStyleRestaurant {
    id: Int!
    restaurant: Restaurant!
    created_at: String!
    updated_at: String
}