type Query {
    appName: String

    getRestaurants: [Restaurant]!
    # Lorsque l'on veut donner la possibilité à l'utilisateur de nous fournir une information complémenaire par rapport à le requête, on utilise les paramètres de la même manière que l'on ne le ferais avec une fonction de type TypeScript
    getRestaurant(id: Int!): Restaurant

    getCookingStyles: [CookingStyle]!
    getCookingStyle(id: Int!): CookingStyle

    getCities: [City]!
    getCity(id: Int!): City

    getManagers: [Manager]!
    getManager(id: Int!): Manager
}