@endpoint=http://localhost:3000/graphql

# test de requête
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query GetCookingStyles {
  getCookingStyles {
    label
    cooking_style_restaurants {
      restaurant {
        name
      }
    }
  }
}

### Création d'un restaurant
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation CreateRestaurant($input: RestaurantCreateInput) {
  createRestaurant(input: $input) {
    id
    name
    restaurant_cooking_styles {
      cooking_style {
        label
      }
    }
  }
}

{
  "input": {
    "name": "test",
    "description": "test description",
    "terrace": true,
    "manager_id": 1,
    "city_id": 1,
    "cooking_style_ids": [1,2]
  }
}